### ISSUE TITLE
How  to prepare my own dataset?

### ISSUE THREAD

**Issue by zhujilin1995** [ahmdtaha/simsiam#8]
Hello, in your code, the dataset of cifar10 is used. But the file of cifar10 python is specialized. I want to use my own pictures to train, how do I prepare? Thank you very much.

**Comment by ahmdtaha** [comment]
Hi Zhu,
It has been a while since I worked on this code.
As far as I remember, create a new Dataset module (e.g., `imagenet`) inside `simsiam/data` following [CIFAR](https://github.com/ahmdtaha/simsiam/blob/main/data/cifar.py) module. 
Import the new dataset class inside [__init__](https://github.com/ahmdtaha/simsiam/blob/main/data/__init__.py). E.g., `from data.imagenet import ImageNet`

provide the `set` [argument](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/pretrain_main.py#L138) to indicate your new Dataset (e.g., ImageNet)
I hope this helps

**Comment by zhujilin1995** [comment]
**Thank you for your reply. I came acoss another problem when I ran the pretrain_main.py, the following errors are shown:**

_Train Running basic DDP example on rank 0.
Process Process-2:
Traceback (most recent call last):
  File "D:\public_program\miniconda\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\public_program\miniconda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Zhujilin\SimSiam\pretrain_main.py", line 66, in train_ddp
    setup(rank, cfg.world_size, start_port)
  File "F:\Zhujilin\SimSiam\pretrain_main.py", line 28, in setup
    dist.init_process_group(
  File "C:\Users\Zhujilin\.conda\envs\simsiam\lib\site-packages\torch\distributed\distributed_c10d.py", line 503, in init_process_group
    _update_default_pg(_new_process_group_helper(
  File "C:\Users\Zhujilin\.conda\envs\simsiam\lib\site-packages\torch\distributed\distributed_c10d.py", line 588, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError_

 **I have tried looking up some solutions in the Internet, but I still cannot find appropriate solutions. Could you please give me some advice to deal with this error? I will appreciate you too much.**

**Comment by ahmdtaha** [comment]
Seems like a DDP initialization error. 
Try to run the code on a single GPU first and see if the error persists. You can do so either by
1. Set the [world_size = 1](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/pretrain_main.py#L132)
2. Skip DDP setup altogether and go directly to `train_ddp`. Basically, call `train_ddp` instead of [`spawn_train`](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/pretrain_main.py#L166C9-L166C20). Make sure to pass the right parameters to `train_ddp`

**Comment by zhujilin1995** [comment]
Thank you, I have settled this issue. 

However, I have another problem. 
When I finished the 799 epoch, there occured an error. I polished the code, and I use the _799-epoch.state_ profile to retrained. But the training accuracy dropped from 89% to 50%. This is different from what I expected. I thought the previous training accuracy would continue. 

So, why did this happen, and how should we handle this situation? I'm a beginner in coding. My questions might be bothersome, and I apologize for that. Thank you very much for your answers.

The training information is as follows:
![图片](https://github.com/ahmdtaha/simsiam/assets/30228178/1fdcccf8-6dc6-475d-9b60-c396bac7d025)

**Comment by ahmdtaha** [comment]
I am not sure if you are referring to the pre-training ([pretrain_main.py](https://github.com/ahmdtaha/simsiam/blob/main/pretrain_main.py)) or fine-tuning ([classifier_main.py](https://github.com/ahmdtaha/simsiam/blob/main/classifier_main.py)) stage?

If you are referring to pre-training stage, you should set either [`resume`](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/config/base_config.py#L127) or [`pretrained`](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/config/base_config.py#L135C16-L135C26). 

I don't fully remember the difference between [`resume`](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/config/base_config.py#L127) or [`pretrained`](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/config/base_config.py#L135C16-L135C26), but at least one difference is that `pretrained` will assume you are training from scratch, i.e., start_epoch=0. Contrary, `resume` will set [start_epoch](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/trn_pretrain.py#L68C9-L68C15) correctly to resume from where the failure happened. In this case, the [`lr scheduler` ](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/trn_pretrain.py#L101) should resume with the correct learning rate, i.e., the one at the crash point and not the initial lr.

If I were you, I would make sure the [resume](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/trn_pretrain.py#L68C9-L68C15) code is executed correctly and both the start_epoch and the lr reflect the state where failure happened.


A similar logic applies with the fine-tuning ([classifier_main.py](https://github.com/ahmdtaha/simsiam/blob/main/classifier_main.py)) stage. Basically, make sure your code executes [this line](https://github.com/ahmdtaha/simsiam/blob/fcdc3a867b8ff5420c8d6ea697d4c77a61efcf6b/trn_classifier.py#L54). Also double check both the start_epoch and the lr.

I hope this helps

**Comment by zhujilin1995** [comment]
This helps a lot, thank you
